### PR TITLE
Added buttons for Ask / Volume

### PR DESCRIPTION
**Pull request by bobgle**
http://i.imgur.com/nfCqmSv.png

I can easily edit those to display any of these values: https://api.bitcoinaverage.com/ticker/global/USD/. I didn't quite know how to properly display the values, so please let me hear your suggestions.

Before loading they'll simply display as "..." then either change to the value retrieved from the API or removed entirely in case they can't load.

### CODE REVIEW

**Comment by sunnankar** [comment]
Nice job.

It would be nice if the 'Ask' could be removed and the font size increased, perhaps 12 or 14 if it will fit. That will make it more readable.

If the font size could match 'Global Volume' and have it all on a single line.

Since there is space, it would be nice to have Difficulty added also. But I would want it to show up like: 'Difficulty 71.9m' and that might be a little more work since I could not find an easy feed for it and do not want to run our own instance of a node just for this.

Think that could work?

**Comment by bobgle** [comment]
I guess you're thinking about something like this? http://i.imgur.com/AtAuKWw.png

Unless I can find some API to pull that from, I'd rather skip it. Also think about your target audience, would they really know what you're talking about when you put something like "Difficulty: 71.9m" at the top of your site? Sure, it's great to have that there, but it only makes sense on a site like BM.

I'm just thinking from a web designer perspective here. The bar is starting to look a bit crowded, so I'd say either fill it completely or try to leave a reasonable amount of whitespace (I'd prefer the latter, it looks nicer).

It seems that Global Volume can also be displayed as a percentage, would you prefer that since it takes up less space and is a bit clearer?

Sorry, I'm not very knowledgeable about the technical or trading aspects of Bitcoin.

**Comment by sunnankar** [comment]
@bobgle That is looking better and I like the grey to offset but it seems a little unbalanced. Can the font go up another size without looking too unwieldy?

I do not think displaying as a percentage would be useful at all.

I agree on finding an easy API pull for it. I think it might be good to use a placeholder even if it is not active. Perhaps to the right of the volume in black and just have it show up as 'Diff. ...'

That will help balance out the color. Also, can switch the Reddit and Email logo. And perhaps change the email background color to a red like the Google+. Then the bar will be much more symmetrical.

It would also be good to have it list the denomination for the volume. Like 'Global Volume 84515.95 BTC'

Thanks.

**Comment by bobgle** [comment]
http://i.imgur.com/N66Ae3x.png or (font-size) http://i.imgur.com/Se0AF1Y.png

Does this look better to you? I've fixed the symmetry, added a bit more spacing and added a functional difficulty display. I don't quite know what Global Volume is talking about but I can add the denomination if you want me to. I can also remove the abbreviation for that if it's not useful, it does improve readability a lot.

**Comment by sunnankar** [comment]
I like this one better: http://i.imgur.com/Se0AF1Y.png

Global Volume refers to the total amount of Bitcoins traded in all all
currencies in the world on exchanges that make the information public and
is denominated in Bitcoin. So, if you could add the denomination BTC that
will help clarify it for readers so they know it does not refer to USD,
EUR, etc.

Can you also switch the positions of the Reddit and Email boxes? That will
help give it more symmetry in the color scheme like a palindrome.

Thanks.

**Comment by bobgle** [comment]
Is the volume correct, though? I'll add "BTC" behind the number for that. Pull request coming in a bit, I've also switched the Reddit and Email buttons. I'll see if I can find better logos for those.

I was also wondering if you need those share buttons on the other language sites as well, I could integrate them there quickly.

**Comment by sunnankar** [comment]
The volume is, more or less, correct. It is only pulling in the USD volume
and does not seem to have the total global volume (177k versus 202k). But I
checked the API and it does not seem to have an easy to feed for the total
global volume and USD is close enough.

I already added it to a few of the other language sites that get an
meaningful traffic. And to make it useful would probably be way too much
work for the benefit. For example, it would need to pull in the price in
the local currency (which may be inaccurate due to thin markets) and also
translate the global volume into the local currency. So, I do not really
think it is worth the effort currently.

**Comment by sunnankar** [comment]
But it does seem that the javascript or something may need to be embedded
in the relevant sites. That way it gets some of them working. Here are the
layouts I added the include file to.

https://www.weusecoins.com/de/
https://www.weusecoins.com/fr/
https://www.weusecoins.com/nl/
https://www.weusecoins.com/pt/
https://www.weusecoins.com/el/
https://www.weusecoins.com/es/
https://www.weusecoins.com/fi/
https://www.weusecoins.com/new-language/

**Pull request merged**
