### PR TITLE
Added new social share buttons

### PR DESCRIPTION
**Pull request by bobgle**
Hi, 

this includes a small share button bar beneath the header which allows users to share any page on some of the big social media sites. There is an unusual commit which I have no idea where it came from (it deletes some fancybox files), you may want to reverse that but I left it in the pull request.

Other additions / changes: 
- Some new Flat SVG Icons.
- Removed redundant share buttons next to the logo.

### CODE REVIEW

**Comment by bobgle** [comment]
Have to fix IE not displaying the icons.

**Comment by sunnankar** [comment]
@bobgle It looks like the Fancybox is from the pre-Jekyll site so I do not think those files will be missed as they were mainly being kept around as a backup. It looks good so I am going to merge it.

**Comment by bobgle** [comment]
Internet Explorer does not display the svg icons for me, I will add a png fallback tomorrow.

**Comment by sunnankar** [comment]
@bobgle Thanks for checking that and I look forward to it. Thanks!

**Comment by sunnankar** [comment]
@bobgle It would be cool if two buttons were created between the Google+ and Reddit for the price and global volume. I think you should be able to pull the Last price from this API. Want to see if you could get that working pretty quickly?

https://api.bitcoinaverage.com/ticker/global/USD/

**Pull request merged**
