### PR TITLE
Checked all pages for ALT images

### PR DESCRIPTION
**Pull request by kripikrili**
Checked all pages for ALT images

### CODE REVIEW

**Comment by kripikrili** [comment]
Added Article
2017-02-06-the-best-bitcoin-casinos

**Comment by kripikrili** [comment]
Updated link to rbf-faq

**Comment by kripikrili** [comment]
Added Article

2017-02-06-best-bitcoin-quotes.md

**Comment by kripikrili** [comment]
Consolidate 2 articles for "best bitcoin quotes"

**Comment by sunnankar** [comment]
@kripikrili The blockquotes on the quotes page need to be fixed. Thanks.

**Pull request merged**
