### PR TITLE
Add Hardblock Australian Bitcoin Buying Service

### PR DESCRIPTION
**Pull request by Daunus**
HardBlock.net is an Australian exchange owned by me. I hope you can accept its listing. I have been operating it for over two years. Ill provide more info in private message.

Logo Image attached.
hardblock

### CODE REVIEW

**Comment by sunnankar** [comment]
Done and added the hardblock.png to the appropriate folder and merged so that is working.

Perhaps on (https://www.hardblock.net/info) you could update the What Is Bitcoin video to the updated version (https://www.youtube.com/watch?v=Gc2en3nHxA4) and add a link to https://www.weusecoins.com on this page? Greatly appreciated.

And any other content you might want to add would be greatly appreciated; like a guide how to buy bitcoins in Australia with Poli as a post in the _posts folder.

Thanks!

**Comment by Daunus** [comment]
Thanks,

I updated the info page and added a link to you guys. There were a few
things there that were out of date.

Using Poli is pretty simple I dont think it really needs a guide and I
would not know how to fill 500 words about it.




Regards,


Daniel Wilczynski

**Comment by sunnankar** [comment]
@Daunus Great updates. I was thinking of a short guide that has some pictures that help walk people through it. It would be a good resource on WUC that could help get Hardblock some more exposure.

Thanks.

**Comment by Daunus** [comment]
Hmm,

I might be able to do something like that. Possibly I might make it more
general about ways to buy bitcoin in Australia, and include a section on
POLi.

Ill see and get back to you within two weeks.






Regards,


Daniel Wilczynski

**Comment by Daunus** [comment]
Hi,

I made pull request https://github.com/sunnankar/wuc-new/pull/243 for post
about buying btc with POLi in Australia.

Hope its useful. Feel free to make any changes or give feedback. I have
link to my exchange in there but I think its relevant in context and I give
link to alternatives. I hope its appropriate.





Regards,


Daniel Wilczynski

**Pull request merged**
