### PR TITLE
Create 2015-4-26-usebitcoinsecurely.md

### PR DESCRIPTION
**Pull request by paulrosenberg**
New file on using BTC securely

### CODE REVIEW

**Comment by sunnankar** [comment]
Thanks.

**Comment by sunnankar** [comment]
@paulrosenberg Looks good. I will make a few refinements. Thanks!

**Comment by paulrosenberg** [comment]
My pleasure.

**Comment by sunnankar** [comment]
@paulrosenberg Please see these refinements since it will help with future articles. The layout header does the formatting and the it is a Markdown file which then gets rendered into HTML. Markdown has some peculiar differences to HTML like ### tag to define headers, etc.

https://github.com/sunnankar/wuc-new/commit/1d9127176c19627ad80caf57a2c2ba748eee2d35

**Comment by paulrosenberg** [comment]
Thanks. Will do.

**Comment by sunnankar** [comment]
@paulrosenberg I changed the URL and Title to 'anonymously' since that is a completely different topic from 'security'. Should fit in better with the theme of the article. Please note if you have any URLs linking to it.

https://www.weusecoins.com/use-bitcoin-anonymously/

**Comment by paulrosenberg** [comment]
Cool.

**Comment by paulrosenberg** [comment]
Just submitted two small docs. These should require less editing of you.
Hopefully none.

One thing I could find how to do was to include graphics. So, attached
are the two images I wanted to use.

Best,

Paul

**Comment by sunnankar** [comment]
Going to need to open a new pull request for the two small docs.

Including graphics takes a little bit of work. You need to have the desktop Git client.

**Pull request merged**
