### PR TITLE
Added profile for Nicola Minichiello and Factom info

### PR DESCRIPTION
**Pull request by nameone**
Added profile for Nicola Minichiello and more info, graphics, and videos to What is Factom?

### CODE REVIEW

**Comment by sunnankar** [comment]
@nameone Nice work!  I got this merged but had to do it via command line. You can check the work on the two pages. I made the following improvements:
1. Kraken.io optimized the images
2. Fixed the images link in what-is-factom.md from imagur to /images/
3. nicola.md - added href to fix the links
4. storj - alt-tag from Kraken to Storj
5. authorurl - s for SSL and end with a / to preempt redirects and increase page speed
6. line 11 - 2.0 projects
7. Added Nicola Minichiello to the Who's Who page

**Comment by nameone** [comment]
My fault I forgot to change the images back to the uploaded ones... Instead of Imgur. Thanks for that. So I think I should a Factom about page next? And maybe add a profile for Peter Kirby to start with.

**Comment by sunnankar** [comment]
@nameone No problem. Yes, a main page for Factom and a profile page for Peter would be good. His interview will likely not be published for a few weeks but it will be transcribed. So would be good to be prepared for that.

**Comment by nameone** [comment]
Sure will get cracking on that.

**Pull request closed without merging**
