### PR TITLE
CoinCorner

### PR DESCRIPTION
**Pull request by brollymook**
Added coincorner to whos-who/index and added a corresponding about page which I will add to when I have finalized neutral content.

### CODE REVIEW

**Comment by sunnankar** [comment]
@brollymook Looks like a good start. It needs to be named: 2015-09-02-coincorner.md

This is because Jekyll builds from the MarkDown (.md) file.

**Comment by sunnankar** [comment]
@brollymook I was thinking of fixing it but I think it may cause you some problems later with making sure you are on the right branch. So, I figure I will let you fix it and resubmit the PR.

**Comment by brollymook** [comment]
Amended the name of that for you there, did you get the pull request okay? Thanks.

**Comment by sunnankar** [comment]
@brollymook Yep, looks good. Thanks for starting to contribute to WUC and I look forward to plenty of more now that you have some experience with the process.

**Comment by brollymook** [comment]
Thanks for your help @sunnankar, greatly appreciated. I will add richer content for the review page soon.

**Pull request merged**
