### PR TITLE
َArabic Voice Over ( MP3 file )

### PR DESCRIPTION
**Pull request by GMA-216**
Hello,

i finish my contribution of voice over, in my native language, you found a link to download the mp3 file

https://mega.co.nz/#!WRIWUKZL!r-kEw5m2mC7gnRBM2zwF_VDtxc9sGZBcZEEMOcbpc1Y

### CODE REVIEW

**Comment by GMA-216** [comment]
i can't upload the mp3 file directly on github, so i upload it on mega, i just leave a link to download the file

thanks

**Comment by sunnankar** [comment]
@GMA-216 thanks for the mp3 file and the small edits on the translation. I am going to see what I can do about getting it set to video now.

**Comment by GMA-216** [comment]
@sunnankar , you welcome, am really like the bitcoin website earn, and am happy to help Bitcoin community to become more famous around world :)

please, can you add my website to the arabic video, when it's online 
this is my website : www.rj-web.onlc.fr

by the way, am a multimedia engineer, if there is any possibility to help with video montage, i will be available, i can make the edition of this video, i have pro version of camtasia studio 7.

last thing, can i upload the video on my channel on youtube, so i can't response on all questions of arabic community ?

Thank you

**Comment by sunnankar** [comment]
@GMA-216 Actually, that would be great if you want to make the video and upload it to your Youtube channel. So long as you leave the entire video in place and just replace the audio then that is a permissible use so feel free to do it.

Thanks!

**Comment by GMA-216** [comment]
@sunnankar  
ok, no problem, but i need the video, without the voice over, just the music and animation, and next i will use camtasia studio, or youtube editor video, to add the mp3 file, and adjust the synchronisation between animation and my voice over, who can send to me the animation and background music ? .
thanks

**Comment by sunnankar** [comment]
I cannot seem to find the source files. I might have to look around for them some more. Not sure where they are.

**Comment by GMA-216** [comment]
ok, because i saw about all video ( with different language voice over), it seem, they use the same source file 
when you found it, please try to send it, as soon as possible, i really want to participate in this project, because, now i have some free time

**Comment by GMA-216** [comment]
Hello @sunnankar 

are you found the source file "video" ?

**Pull request merged**
