### PR TITLE
First post to We Use Coins "Choice in Money Allows for Freedom of Association"

### PR DESCRIPTION
**Pull request by AdrianChilders**
Hi 

Writing my first post for We Use Coins. Let me know if anything needs to be revised.

### CODE REVIEW

**Comment by sunnankar** [comment]
@AdrianChilders Looks good and well written article. Thanks for the contribution and I hope you add more. Here are a few suggestions that I have cleaned up:

1. published tag needs to be 'true'
2. Made a proper URL on your bio page for both the authorurl and your blog
3. Changed the authorurl on the article to your WUC author page since assume you wanted that

**Comment by sunnankar** [comment]
Additionally, both of them needed a proper date format with 2015-08-04- leading the article title. They also needed to be in the _posts folder so I moved them there.

**Comment by sunnankar** [comment]
And for consistency I changed the file name:

2015-08-04-choice-in-money-allows-for-freedom-of-association.md

**Comment by AdrianChilders** [comment]
Great! Thanks for correcting and merging. This is my first contribution on Github. I'm not a programmer so I'm happy to work with Github to write articles in English. 

So where can I see my post on the WeUseCoins site?

I look forward to writing more articles soon!

**Comment by sunnankar** [comment]
You are getting it and looking for more!

Jekyll to builds the site and is basically takes the filename and strips out the date and extension. For example:

https://www.weusecoins.com/choice-in-money-allows-for-freedom-of-association/
https://www.weusecoins.com/adrian-childers/

At the bottom of the post you can see how it uses the date (first part of the filename), authorurl and author fields.

It would be great to get your author page spruced up. Here is an example of Airbitz's:

https://www.weusecoins.com/airbitz/

**Pull request merged**
