### PR TITLE
Add opendime

### PR DESCRIPTION
**Pull request by nvk**
This pull adds Opendime

### CODE REVIEW

**Comment by sunnankar** [comment]
@nvk Had to fix the page build failures caused from the tabbed characters. It is live now.

https://help.github.com/articles/page-build-failed-invalid-yaml-in-data-file/

**Comment by nvk** [comment]
Thx!

**Comment by sunnankar** [comment]
@nvk Glad to help. Feel free to submit more pull requests. Perhaps it needs an update?

https://www.weusecoins.com/rodolfo-novak/

**Comment by nvk** [comment]
That still good, but I will review the site for other contributions I can make.

**Pull request merged**
