### PR TITLE
Change Ad. link because suspended sales of S9.

### PR DESCRIPTION
**Pull request by corper**
Suspended sales of S9.

### CODE REVIEW

**Comment by sunnankar** [comment]
@corper Do you want this change done on BM also? https://github.com/sunnankar/bm

**Comment by corper** [comment]
@sunnankar  Yes. Thank you very much.

**Comment by sunnankar** [comment]
@corper Are you going to make the pull request or do you want me to? In the future, it might be more efficient if you do the pull requests on both repos.

**Comment by corper** [comment]
@sunnankar I'll pull request by myself. Thank you.

**Pull request merged**
