### PR TITLE
Bitcoin VPNs: Add FastestVPN

### PR DESCRIPTION
**Pull request by webwizo**

### CODE REVIEW

**Comment by webwizo** [comment]
Thank you for your quick action.

**Comment by sunnankar** [comment]
@webwizo Thanks. If you could have the person in charge of the affiliate program email trace @ weusecoins.com it would be appreciated so I can get that setup.

**Comment by webwizo** [comment]
Can you please describe more so that I can get the detail regarding affiliation program?

**Comment by webwizo** [comment]
@sunnankar I think there is something wrong with the price.
Monthly: 7.99
Yearly: 23.99

But your site showing yearly price in monthly tag, can you please fix it?

**Pull request merged**
