### PR TITLE
Two About Articles

### PR DESCRIPTION
**Pull request by paulrosenberg**
Hopefully formatted better.

### CODE REVIEW

**Comment by sunnankar** [comment]
Can you make a few changes:
1. File name - 2015-05-04-cryptohippie.md
2. File name - 2015-05-04-paul-rosenberg.md
3. authorurl (both pages)- https://www.weusecoins.com/paul-rosenberg/
4. Can you add the WUC affiliate link to the About Paul page? Thanks.

Jekyll needs the date leading on posts in order to build the pages. The s and / will preempt redirects and speed up page loads for visitors.

Looking good.

**Comment by paulrosenberg** [comment]
Will do.

**Comment by sunnankar** [comment]
The first paragraph in About Paul needs the WUC affiliate link. The two files that are not used actually need to be deleted.

I can merge it and then make both of these changes. You can just keep that in mind for future content.

Thanks!

**Comment by paulrosenberg** [comment]
Got it. Thank you.

**Comment by sunnankar** [comment]
I also added these two pages to the Who's Who page.

https://www.weusecoins.com/en/whos-who/

Would be nice if all these came in perfectly edited in one commit ;)

**Comment by paulrosenberg** [comment]
I shall endeavor to improve. :)

**Pull request merged**
