### PR TITLE
BlockTrail addition for who's who section of weusecoins.

### PR DESCRIPTION
**Pull request by alnxdr1**
Founder image, logo and Author URL and Company information included.

### CODE REVIEW

**Comment by sunnankar** [comment]
@alnxdr1 Looks good.

I made a few optimizations with (1) image name for boaz's picture, (2) resizing the logo to 700px like other images and (3) optimizing the images using www.kraken.io.

**Comment by alnxdr1** [comment]
Thank you!

**Comment by alnxdr1** [comment]
Any update on this? Thanks.

**Comment by sunnankar** [comment]
@alnxdr1 The pull request got merged and the content is live. Then I changed the image file name, resized the logo picture and optimized them both with kraken.io.

Not sure what else you had in mind for updating? There are no other pull requests to handle.

**Comment by alnxdr1** [comment]
Thanks for the optimization of the images. I fail to find the live content
on the site, I checked all the links. Maybe it's on my end?

On Mon, Jun 8, 2015 at 5:13 PM, sunnankar <notifications@github.com> wrote:

> @alnxdr1 <https://github.com/alnxdr1> The pull request got merged and the
> content is live. Then I changed the image file name, resized the logo
> picture and optimized them both with kraken.io.
>
> Not sure what else you had in mind for updating? There are no other pull
> requests to handle.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunnankar/wuc-new/pull/72#issuecomment-110033433>.
>



-- 
Kind regards
Alejandro De La Torre
<http://www.alxndrmgmt.com> <http://www.alxndrmgmt.com>

**Comment by sunnankar** [comment]
Both links work fine for me.

https://www.weusecoins.com/blocktrail/
https://www.weusecoins.com/boaz-bechar/

**Comment by alnxdr1** [comment]
Okay thanks! Where can these links be found however? I don't see them at
the who's who section.

On Mon, Jun 8, 2015 at 5:49 PM, sunnankar <notifications@github.com> wrote:

> Both links work fine for me.
>
> https://www.weusecoins.com/blocktrail/
> https://www.weusecoins.com/boaz-bechar/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunnankar/wuc-new/pull/72#issuecomment-110050546>.
>



-- 
Kind regards
Alejandro De La Torre
<http://www.alxndrmgmt.com> <http://www.alxndrmgmt.com>

**Comment by sunnankar** [comment]
I don't think you submitted a pull request for the Who's Who page.

**Comment by alnxdr1** [comment]
That make's sense, on that now. Thank you and sorry for all the questions.

On Mon, Jun 8, 2015 at 5:59 PM, sunnankar <notifications@github.com> wrote:

> I don't think you submitted a pull request for the Who's Who page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunnankar/wuc-new/pull/72#issuecomment-110053012>.
>



-- 
Kind regards
Alejandro De La Torre
<http://www.alxndrmgmt.com> <http://www.alxndrmgmt.com>

**Pull request merged**
