### PR TITLE
Update and rename 2015-04-21-what-is-factom.md to 2015-04-28-what-is-fac...

### PR DESCRIPTION
**Pull request by nameone**
...tom.md

Nic here at Factom. Updated the What is Factom post with more info about Factom, Factoids, added more videos and graphics. I would like to add the pics to the /images/factom but don't have access to that. For the moment pics are loaded from Imgur. Also don't have a profile on here so I used the Factom Website as the Author URL. If anything doesn't look right or want it changes please reply to this commit. We would like to add more posts and having write access to the repository would help. nic@factom.org if you need to get in touch. I can add more info to this post too but want to make sure it looks fine before I do so.

### CODE REVIEW

**Comment by nameone** [comment]
Nic here at Factom. Updated the What is Factom post with more info about Factom, Factoids, added more videos and graphics. I would like to add the pics to the /images/factom but don't have access to that. For the moment pics are loaded from Imgur. Also don't have a profile on here so I used the Factom Website as the Author URL. If anything doesn't look right or want it changes please reply to this commit. We would like to add more posts and having write access to the repository would help. nic@factom.org if you need to get in touch. I can add more info to this post too but want to make sure it looks fine before I do so.

**Comment by sunnankar** [comment]
@nameone, thanks for the commit. It is a great start but needs a little refining. Using the desktop client (using the desktop client instead of the web should solve many of your problems) instead of the web may solve many of your problems.

By the way, had a good interview today with Peter Kirby for the podcast and a David Johnson appears to be doing great. When the interview gets edited and transcribed then it will be good to have an About page for the Factom Project and another for Peter already setup. Perhaps you can take care of that?

Here are some suggestions to better optimize the content for inclusion:
1. Images can be added to the Github repo (use desktop client and clone repository)
2. Images should have descriptive filenames (ex. factom.jpg instead of k6GbyTb.jpg)
3. Images should be compress optimized to reduce page load time (www.kraken.io; 72.82% reduction on 5PAIIEf.png)
4. Images should be no larger than 700 pixels width. If they are smaller then it would be good if they were formatted to look well in the articles (centered, etc. as appropriate for design aesthetics).
5. We should try not to change the filename without a good reason. In this case, changing the date has little practical effect but causes the diff to be a lot more work and potentially messes with the project repo branches.
6. It would probably be good for you to create an About article for yourself and Factom Project.
7. Let's keep the 'author' to a proper noun. Perhaps your name or Factom Project.
8. Let's keep the 'authorurl' to either your About article or the Factom Project About article.
As a suggestion, I think it would be good to include links to other articles or content in the About articles and add a link to the alt-coin/index.html to the Factom Project About article. If you use your name then perhaps you can still create the Factom Project About post, fill in some of the leadership team and create an About page for yourself that is linked to from the Factom Project About article. This type of a structure will enable the articles to be more easily found which will result in greater exposure and traffic; particularly from the search engines.
9. Good job with the Youtube embeds being 700 pixel width like images should be.

Nice job overall. I think with those few changes and optimizations then the article will be in much better shape. Plus, you will be able to make future articles optimized from the beginning. I look forward to merging the commit when you get those cleaned up.

If anything is unclear then please let me know.

Thanks!

**Comment by nameone** [comment]
Yes I did try to add a folder to /images/factom/ with all the pix in there but came up as no permission, I will have to clone it as myself then possibly submit all the pix as a pull request? I had a look at the previous post and figured the pix and video dimension, no worries with that and I had named the actual pics with descriptive names. Had to use Imgur as I wasn't able to upload them to the repository. I would like my name to be on the posts so I can add a pic of myself together with a Factom logo, so the author name could be me and the URL factom.org or if I can also setup profiles for Peter Kirby, David Johnston, Paul Snow, etc I can use their names when required if they write something or if there is a video about themselves. I'm happy to link other content available on this site within my posts, just a little hard not having write permissions. Also I am a full team member on Storj and Synereo teams + do a lot for SWARM, Spells of Genesis so I could add posts about them too. Just to make sure I'm doing things right, the code is markup with extra HTML code for Pix and Videos?

**Comment by sunnankar** [comment]
I have had issues with the permissions also. I think I usually just fork the project, submit the pull request to the fork, then merge it and then am able to submit the pull request to the main project. Really wish I could better understand Github so it might just take some tutoring form someone who is a little more competent than I.

Sounds like a great plan with setting up profiles for everyone and for the other projects you are a member on. I really like the SoG artwork! Hopefully we can get the Github usage issue shorted out.

Yes, it is Jekyll hosted using Github Pages and I think it is in Markdown. This should help further explain:

http://jekyllrb.com/docs/posts/

**Comment by nameone** [comment]
Will submit again

**Comment by sunnankar** [comment]
Thanks. Got the new submission, made a few improvements and got it merged.

**Pull request closed without merging**
