### PR TITLE
Made the site more responsive and converted image to html / css

### PR DESCRIPTION
**Pull request by bobgle**
More responsive by making the videos not extend past the site's boundaries. The image is now a table which is easier to edit and looks very similar to the one that was there before.

### CODE REVIEW

**Comment by bobgle** [comment]
The brackets are somewhat misaligned on Internet Explorer, I don't think it's a huge deal but I'll try to fix it.

**Comment by sunnankar** [comment]
@bobgle In the future, can you please try to make it so unnecessary parts of a commit do not get included in the PR? This makes it easier to review. Not sure if everything in the #2 from Dec 22nd needs to be included in this PR. Might be a result of not having synced the repo before submitting the PR.

Thanks.

**Comment by sunnankar** [comment]
@bobgle Looks like the table formatting also needs to be cleaned up a little bit.

**Comment by bobgle** [comment]
@sunnankar I think the unnecessary (empty) commit got added after I submitted the pull request. Luckily it was empty this time, so it has no impact on anything.

**Pull request merged**
