### PR TITLE
Closing the Circle

### PR DESCRIPTION
**Pull request by goethewins**
Uses the example of the 13 American colonies to answer the foundational question, "what is money"

### CODE REVIEW

**Comment by sunnankar** [comment]
@goethewins  thanks for the commit. It is a great start but needs a little refining. Using the desktop client instead of the web may solve many of your problems.

Here are some suggestions to better optimize the content for inclusion:
1. Images can be added to the Github repo (use desktop client and clone repository [gh-pages branch!])
2. Images should have descriptive filenames (ex. factom.jpg instead of k6GbyTb.jpg)
3. Images should be compress optimized to reduce page load time (www.kraken.io; the slides_whatismoney.png is not feasible being 1.2MB)
4. Images should be no larger than 700 pixels width. If they are smaller then it would be good if they were formatted to look well in the articles (centered, etc. as appropriate for design aesthetics).
5. We should try not to change the filename without a good reason. In this case, changing the date has little practical effect but causes the diff to be a lot more work and potentially messes with the project repo branches.
6. It would probably be good for you to create an About article for yourself and there is a Paxul page already.
7. Let's keep the 'author' to a proper noun. Perhaps your name or Paxful.
8. Let's keep the 'authorurl' to either your About article or the Paxul About article.
If you use your name then perhaps you can still create the Paxful About post, fill in some of the leadership team and create an About page for yourself that is linked to from the Paxful About article. This type of a structure will enable the articles to be more easily found which will result in greater exposure and traffic; particularly from the search engines.
9. The file should have a header for layout purposes and author attribution (variables fill in the author byline). It should be based on this:

---
layout: post
title: Paxful About Page
author: Paxful
authorurl: http://www.weusecoins.com
published: true
---

10. Perhaps you can turn line 78 into a properly structured link.
11. Perhaps lines 79-83 can be deleted since the byline will be shown there and link to the authorurl.
12. Good job with the Youtube embeds being 700 pixel width like images should be.

Nice job overall. I think with those few changes and optimizations then the article will be in much better shape. Plus, you will be able to make future articles optimized from the beginning. I look forward to merging the commit when you get those cleaned up.

If anything is unclear then please let me know. Same principles and suggestions apply to #25.

Thanks!

**Comment by goethewins** [comment]
Hi,

Sorry for the trouble.

Made a corporate bio page. Is it too spammy? We are working on more videos.

Did another post on security. The images are linked offset and all are
700px wide or smaller. Github desktop client is kaput for mac osx so will
work on uploading those images. Is a new folder under /images/posts
 alright?


-Ray

**Comment by sunnankar** [comment]
Corporate bio page should be: paxful.md

The images should go in the /images folder. No need for an /images/posts folder.

My mac OSX Github desktop client is working just fine. Are you sure it is kaput? Need to have the images on Github for page speed and to reduce requests which both help optimize the speed of the site.

Thanks.

**Comment by sunnankar** [comment]
@goethewins Due to these not being updated and optimized I am closing them. Please feel free to resubmit when you have them to a professional level. Thanks.

**Pull request closed without merging**
