### PR TITLE
add Boaz Bechar to whos-who as CEO of BlockTrail

### PR DESCRIPTION
**Pull request by alnxdr1**

### CODE REVIEW

**Comment by sunnankar** [comment]
@alnxdr1 Looks good.

**Comment by alnxdr1** [comment]
Thanks, we've shared it on social media.

On Tue, Jun 9, 2015 at 6:23 PM, sunnankar <notifications@github.com> wrote:

> @alnxdr1 <https://github.com/alnxdr1> Looks good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunnankar/wuc-new/pull/74#issuecomment-110421775>.
>



-- 
Kind regards
Alejandro De La Torre
<http://www.alxndrmgmt.com> <http://www.alxndrmgmt.com>

**Comment by sunnankar** [comment]
Great.

If you want to contribute blog posts or articles about some of the more technical aspects of Bitcoin then it would be greatly appreciated since we want this to be a good resource for the Bitcoin community. Additionally, the articles will likely get good exposure, perhaps more than if they were published on Blocktrail.com, from long-tail searches.

Thus, it may be a good way for developers and enterprise users to find out about what Blocktrail does.

Thanks.

**Comment by alnxdr1** [comment]
That's something we would love to do! Let's keep in contact. If we do have an article, where should we do the pull request to?

Thanks

**Comment by sunnankar** [comment]
You can create an article in the _posts folder just like you did for the about pages. It would probably be best to use Blocktrail as the authorurl so the articles build the authority of that page. It would also be good to have some internal links to the articles so you can probably find something in the FAQ (questions folder) to link to it.

Additionally, I also maintain Bitcoinmining.com so if you wanted to submit technical articles over there then you can. If so then you will probably want to link them on the Blog page so they get more exposure. Would probably still be good to use the Blocktrail About page on WUC as the authorurl since that will help build that page's authority and will eventually be your other search ranking for the brand term which should help you with your marketing.

Looking forward to the pull requests!

**Pull request merged**
