### PR TITLE
New translation organization and filters for some pages

### PR DESCRIPTION
**Pull request by leon-wbr**
This PR adds the new translation organization. It might have a few 404 links or dead backlinks now, as I changed a few of the German permalinks for testing. Most of the file structure is kept, there are a few unused languages which still need to be ported. I deleted a few untranslated pages (they were copy pasted from English), this might create a few more dead backlinks, too. Not sure if it makes sense to keep them - they will be replaced with new translations, having relevant permalinks.

I think it might be needed to verify that relative links are still correct - I think most of them are, but I don't know my way around the site as good as you do. The [current testing site](http://www.learnbitcoinfast.com/) has the exact same code in use for you to review.

Filters were added to the VC Investments and VPN pages. I decided to put [the script up on GitHub](https://github.com/leon-wbr/jekyll-filter.js), there is a little documentation on how the script is used available in the readme there, if you're interested in adding the functionality to other pages. I think it is not possible with the way the exchange page is currently set up.

### CODE REVIEW

**Comment by leon-wbr** [comment]
We may want to be careful with the merge - definitely make sure that the data files won't get unnecessarily overriden, at the very least. The merge conflicts I had to fix were quite unusual.

**Comment by sunnankar** [comment]
@leon-wbr Will wait for you to fix the broken issue. With some of the non-translated pages the videos do show up in the languages so those would want to be kept.

**Comment by leon-wbr** [comment]
@sunnankar Those are kept of course - it's about the sub pages of some languages, such as getting-started or mining-guide. [Russian](http://learnbitcoinfast.com/ru/) is a good example for this, you can see what it'd look like if only two sub pages are translated.

**Comment by leon-wbr** [comment]
There is a new version live on http://learnbitcoinfast.com. Check there and tell me if you'd like anything changed or fixed. I couldn't tell anything not working. Definitely check out filters. http://www.learnbitcoinfast.com/en/venture-capital-investments-in-bitcoin-and-blockchain-companies/

**Comment by sunnankar** [comment]
@leon-wbr Looking good. Thanks.

**Pull request merged**
