### PR TITLE
Added blockonomics

### PR DESCRIPTION
**Pull request by shivaenigma**
Added to list of companies

### CODE REVIEW

**Comment by sunnankar** [comment]
@shivaenigma Got it taken care of.

Perhaps you could please add a link to https://www.weusecoins.com somewhere on this page (https://www.blockonomics.co/views/faqs.html)?

Thanks!

**Comment by shivaenigma** [comment]
@sunnankar thanks you. I will add wuc to faq and let you know!

**Comment by shivaenigma** [comment]
Added to our faq https://www.blockonomics.co/views/faqs.html

**Comment by sunnankar** [comment]
@shivaenigma Awesome, thanks!

To get more exposure you could create and beginner guides, etc. and that would be great. You can also create Company or People pages.

https://github.com/sunnankar/wuc-new/tree/gh-pages/_companies

https://github.com/sunnankar/wuc-new/tree/gh-pages/_people

**Pull request merged**
