### PR TITLE
adding Edge wallet

### PR DESCRIPTION
**Pull request by chadyo**
We are adding Edge Wallet to the list of available wallets. Edge was created by the team at Airbitz, which is also listed here and is still available so no modifications needed to that existing listing, just adding Edge.

### CODE REVIEW

**Comment by chadyo** [comment]
@sunnankar I'm a little new to this process. Any estimate you can give on when this can be merged in and pushed to the live site? Thanks!

**Comment by chadyo** [comment]
@sunnankar I see on the page https://www.weusecoins.com/en/find-the-best-bitcoin-wallet/ the Mobile Wallets for Android & Mobile Wallets for iOS sections are now blank since the latest site change. Is this expected?

**Comment by sunnankar** [comment]
@chadyo No, not intended. I wonder if the category is being pulled correctly.

**Comment by chadyo** [comment]
@sunnankar I found out what the issue was. The formatting of the wallets.yml got messed up when someone recently checked in the atomic wallet. I fixed this and submitted pull request: https://github.com/sunnankar/wuc-new/pull/642

Let me know if this fix and this "Adding Edge Wallet" pull request can be merged. Thanks!

**Comment by sunnankar** [comment]
Thanks. Merged #642

**Comment by chadyo** [comment]
@sunnankar is there a reason #627 was just closed? #642 was the fix I put in yesterday, #627 was never merged.

**Comment by chadyo** [comment]
@sunnankar any update? Can you reopen #627 ?

**Pull request closed without merging**
