### PR TITLE
Research library fix & table

### PR DESCRIPTION
**Pull request by leon-wbr**
This fixes the research library and puts the data into a prettier table.

### CODE REVIEW

**Comment by sunnankar** [comment]
@leon-wbr Links appear to be working now. Looks like the formatting may need to be cleaned up a little but that might be a caching issue on my side.

**Comment by leon-wbr** [comment]
@sunnankar [It should look like this.](http://i.imgur.com/JdOY3cu.png) Descriptions and authors take up a lot of space, I might decrease their font-size as well as reduce the space taken up by file size.

**Comment by sunnankar** [comment]
@leon-wbr Yep, it was a caching issue. I think the font sizes are fine.

Is there any way you could add some formatting, like a box or line, that separates each paper with its information. That will make it easier for the users.

To save space perhaps move the Date and Size in the same row under Title and above Description instead of having them as separate columns.

Thanks.

**Comment by sunnankar** [comment]
Perhaps something like this:` <hr style="width: 100%; margin: 20px 0; color: #eee;" />`

**Pull request merged**
